openapi: 3.0.3
info:
  title: ZK Ticketing API
  version: 0.0.1
servers:
- url: http://localhost:3000/api/v1
paths:
  /health:
    get:
      responses:
        "200":
          description: The API is healthy
      summary: Check the health of the API
  /events:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Event'
                type: array
          description: List of events
      summary: Get list of events
  /events/{eventId}:
    get:
      parameters:
      - explode: false
        in: path
        name: eventId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
          description: Event details
      summary: Get event details
  /users/request-verification-code:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEmailVerificationRequest'
        required: true
      responses:
        "200":
          description: Verification code sent successfully
      summary: Request an email verification code
  /users/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
          description: Login successful
      summary: User login
  /users/me:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User details retrieved successfully
      security:
      - bearerAuth: []
      summary: Get user details
components:
  schemas:
    Event:
      example:
        admin_code: admin_code
        name: name
        description: description
        id: id
        url: url
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        admin_code:
          type: string
      type: object
    UserEmailVerificationRequest:
      example:
        email: email
      properties:
        email:
          type: string
      type: object
    UserLogin:
      example:
        code: code
        email: email
      properties:
        email:
          type: string
        code:
          type: string
      type: object
    LoginResponse:
      example:
        token: token
      properties:
        token:
          type: string
      type: object
    User:
      example:
        encrypted_internal_nullifier: encrypted_internal_nullifier
        identity_commitment: identity_commitment
        encrypted_identity_secret: encrypted_identity_secret
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        email: email
      properties:
        id:
          type: string
        email:
          type: string
        identity_commitment:
          type: string
        encrypted_internal_nullifier:
          type: string
        encrypted_identity_secret:
          type: string
        created_at:
          format: date-time
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
