apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: proof-pass-app
build:
  artifacts:
    - image: oyyblin/proof-pass-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
    - image: oyyblin/proof-pass-backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: oyyblin/proof-pass-issuer
      context: issuer
      docker:
        dockerfile: Dockerfile
profiles:
  - name: local
    manifests:
      kustomize:
        paths:
          - infra/k8s/local
  - name: production
    manifests:
      kustomize:
        paths:
          - infra/k8s/production
    build:
      local:
        useBuildkit: false
        push: true
