apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: proof-pass-app
manifests:
  rawYaml:
    - infra/k8s/frontend.yaml
    - infra/k8s/backend.yaml
    - infra/k8s/swagger_ui.yaml
    - infra/k8s/issuer.yaml
    - infra/k8s/postgres.yaml
    - infra/k8s/redis.yaml
    - infra/k8s/gateway_frontend.yaml
    - infra/k8s/gateway_api.yaml
build:
  artifacts:
    - image: oyyblin/proof-pass-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
    - image: oyyblin/proof-pass-backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: oyyblin/proof-pass-issuer
      context: issuer
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    defaultNamespace: app
profiles:
  - name: local
  - name: production
    build:
      local:
        useBuildkit: false
        push: true
