apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend
  namespace: app
spec:
  encryptedData:
    BACKEND_JWTSECRETKEY: AgBtJULGG7wFjbt6rUlnCIufJRIs1dP4MxxnWw1CIWpp4W7aO4V2xTGG3S00+JSPwc9Q1qerylTMnPR5Py333+aUDHgQsEd3HcHlsOsHE2QjzeYlwJxVrZ+prhdg8tkotGjsmsNQw2u0JziAx0yo1u4gQOyA/erXfl/zz/bg0i/ter3vcROHxlpDHBUcJigzNwHAW3RC/HHoyWx9crJzU7Lm3cyb6fsIQxiznY+mkwYtkRrMdqgzLgLEYEluV0WdzPlPH74JcvUkniU1OPXSMCTDQQPmPw14mAeg+U/KLaZDkueZbqvAWswdwM3O8mB6QrAkNKzh73fAIu9LkkueB54ugUDr2b1EoWKXk8xkK/gZ9y7h7FUXeb1IqxUk8HNVZOBncMimv3AMY7KW0JAXiS9coYex7AYkkfcpVxwirmM6DSCal5h/2WL/Tr5dUXRb+Gs5OASrV1+ElLvHJRiusWg9uUbBJjQnp1UoE059rOB31RC+roKbhoA8ig8ubnGE0bcjk7+tMnaqHV86QSZ0R0vsnRlH4GbhaNde5dUCM79h1uYyCsMV570X/40XpTR6JLMj5MLRGP5E6DuuoNZKK9DvCOeiu6pwYErR1FoIJNGRyAP878ufxcKJWT4tXr85cqg89ffjJToOL8BQKkucFaFVC5vmoDXzOdMEpO5zzC/NJjV8+2ekapf59DJe8IkcOV16LtZV3LHjA/bj393N5qPjq4TlgKIxo6fsKvmq
    BACKEND_POSTGRESPASSWORD: AgAsm0BnHjvittrmuKmtjIvBof+pS8FXdYQzEgEJpfHL5qwqyYy1ewUQRcN9YQ7N/lCB5JYeqwc3eBxzWrrtsI3/qIa/Xk0W0tnzyJE1uWU3eDAUWKaoDtjKoAGzyqVXiZ5ab3LiazxGcdsRO+wzUHBzuwtX23xyXCP5uaQkQY6JGwA1DPYNxl6cVFCJkN6uxFvjlHNRSjGSfB2GC88M3obAEx7phxmZqAmkS/5a4uOxbZwy8zxX4Jza9N9X7rzI7OJ5FknDcjM3lZUeSiHpqe1gNS1VLmRWoN3/Eb2MxIpaS7kH8ARGP/iTxJ5HoDH9BEu3iQbWDMyvCKb0CtAIw35vzZ/v+EHG7qo2GQMXmwi99tQ9di4pr/eCON2NMTOnosAP5BwUAVsm27IUoIirX86dHdSB7AmvRFmsbQaCATlCupGncmOxOTIcVTjYbnqcKMdzDPgzOU1UX6zuWcPpMo+woDzkQrm7axuJ7rr/acXpAhNk9Ao92bxapXvx1C7G2MYADgv2XSybYdOe3ukuXbjDMBEVThEhXqEBceyaYBwGccYIyP53YPL5FzYAR8JRp1H34YltR9vfKGN/hGmU39RnTiyPMWnNzIL1vIB4OmyNkGq2PRt78mfhimduEL60wN2W1tKT0vMXHzbhQpn6GO+LADJBpK3kUWJWj6jJcyadpFsSrgylyYQShx1NmBmIQAdg7XmpnMfaDg==
  template:
    metadata:
      creationTimestamp: null
      name: backend
      namespace: app

