apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: issuer
  namespace: app
spec:
  encryptedData:
    ISSUER_PK: AgBj+t5Q5zimCJbjo9Cthun9eZz8xd/aWSE4V8vR8DK8J5Ql8QG8m0gDB0YaUPvDBr18jMfChbwQuIZCmCAKL/kwOtBKlh9eQAbpuO2byiphJeCPIbHwWkeOCSKarnN15lHYiWXM7IIVI8Rw3cR0MIAqMCGnNKpNfM/Rr7Q4gSZ+132uAobD44cZ1JoqNtUQ57FfCDPDTv8zRvkY1bJBzUSVIzVS2C27XSU1e+NkR1pslO1aLgrhjf/ZITnyomuoldGXwF3fD06iJiTvNpHD0tGkAmeA8bIvCU3q8q0tWuxxwDEg3QqftFLYQuCo+63jF/0KPS79HV5r7I6QcWGXfr6inr0JPVpGBLoIdzVbT6DefQE9OJELK4As94xV17BeQ9QbWfjpYpPiquhsnEDFDIsiBHxPZozLKNY8JFUUn3tXBiHfy9FERmALsq9iRCJZq7l5MD4ra1CNnv04qogA0GIXpeHRWGhsu1UCHL2dH6yhb2Y5mKfYlx529/0r6SkU6pguj2A/juhHH9OtFmc5XXzOQsQ6AJfPjA0Xv/rUaNM1938nzRkym9ZllRANl9fdnhmquB+RUe/dtZ+YSJOhA4PuDytIzk9r9MPeoKvu1xkbveZtOjhG5Vj63k6pMRH60LrSv0MyRJXOjyPHTvIkCZ1HFUIDLqZjXs08Jx8Px/uhWWZgzG68a/3ISIbskdAed8lTGFuZ3Mv9NLtY49GDzdgD+fDLup/65m0jU5xeKMHJc3JItM88MeZJhQAeKVfOXE2UtmEncgoE+3r1aXH7IglhsRA=
  template:
    metadata:
      creationTimestamp: null
      name: issuer
      namespace: app

