apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: issuer
  namespace: app
spec:
  encryptedData:
    ISSUER_PK: AgAcZUhx8lmsr6vGe5Ijqw0mO8BtvPQab3lSb9ZCPQp4bV56RM1AjWnrfh2a70rmJMh6rsu86wq4ht2ftgUmxEJcKoBnEIWgzjWO+ivJF0+OwuhhMBQW6k7t7dnoqD4PHPVC+SRsdhYJjdK1wc3CCnyQoAf5vSy/XdWeHnL9fghFhKaQSdMXxgxLO6Yaa5syvcdslokh1ugCQQjl/oWijNV2v3FNAqtF9czBfGg+rTYh4/4pblMKxRU3rWZGfVbRJSR3SE3yeZVEaaKt30EhieMW/YNi5tKw/aaPgKO7HfaopWoQSdtptIkKywcZ2M3I4SoAQmRzEOWb1YR0pxxdOdFW6MqQPWYly85rd9hHyRXoa5hOo9k72tP4e5FGgcr9wnZMEGXqnqW6PMIXLFPCix4ss/2fcbyPZdhN+jsAv5QF53aNFy9whArG/IwSbwSfRI3bv8V046Ts9p/z/2tbkMb9AmYu2DghUvH8qbLw4BTaiOJmZx92l8K+KXT4d6lq1SeDNU6+ueX9qE8ANCb3kBw3xLcR2LLfWraihVWg6RZ3GYvgdew2rxG84SxivyhNvORDOfyVLYj7Jhqkl2aOQ3n9Ol+9ha7qiI+MzeoYAnnCjnuANMZwnuKYyqF9ZDZkMDkNP/OPTiK8WcP1Wj4EWf2nfslJiByh6etKvySyZZTJmsNcpVj40Ra/shwexi6iVObKp4G2dLepuxE3RlqxdMDbCEUUpS4g301DXLVxvqDNjttTf/iUpEF20P3X9oB471w5xL7dhnf02qpPJiHLz/g4yJuBXgcico07SJ01AFp4Wu7yC+byif51
  template:
    metadata:
      creationTimestamp: null
      name: issuer
      namespace: app

