apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: issuer
  namespace: app
spec:
  encryptedData:
    ISSUER_PK: AgBQu2BG3afilmEH2W8BUueIPFNVNuqzrBOWhPKagGQyshGghmu3kXHyW/T2qUAAU1G6rTsc6mVaXICkhj2HBbyJ+qjSrOecMdTJpOyWGv47ZUORFRcsGUrIfJ8Q4nbGPdnZrR/ul0H/cDKy+GVyA5/C3VK4N9MxOBR3G2QiNuUyjFhywewHM3vHEBm+FXCiDqCWXOykJ9byoYSnRb1p+Q0tOxwhLoFFOPMmccg+Sx7/Atekb7Wm9mHtcl4/v2drXZEh2qP6GmB2PAeAzIJgWZ8cuDbD2BC7m/YQNOPKMKiYRorVDt6NXd+TcOzee8qu4zoePjrsK+TOAj09OjcPKXGim3kWByB3Et9cCUkauqcIeigEJOoxvOvxjoR5ZCezJmSBpTjaUY1gtHeB518Jg5bBKQ1tu343DlBCGQ3WaBJ/RSw13WSEqOGBxoIH/DVZ3AjnM+NIkS84io4QO/r3XYjzfJMHJDxixYEhufQBh5uYpfKHJmADo+JXA8nwm4e136r5UblCu+Ba+pxD5Vk9baUZOzUNwWU24O2tv95tLjXfdIlyA1jT91Cea2s9ZmiQ76eGif6UXNTKz+y+LnWWTlt2fIWVUvmao9prBm9F80k99RDy1LzR8CULkvUGjbqg9G2yXCxKJHEJxGc3vfXy6FetMjHbINhTGurGivxMXIEDgqo3tzuFDxQsMMp1hbUcn5MzoV6rnZCfByMZG5Rqa6sHZtGhGegc+cI8r0Yyyh1mkbsaZxFDaA1hB4m22p7ZchGagvIKkmzEQ71q9FmKh/ZtdflEZmFiImUCD2JD7GKqug3lwG1z1QXo
  template:
    metadata:
      creationTimestamp: null
      name: issuer
      namespace: app

