apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: app
spec:
  encryptedData:
    password: AgCJj/en1gMbTcWFOCARyXs/lOOJY193iqzllQ0hwcpzs0j3JAoNrJVl8wEiFlkWvjZ7RhqIbi5BkqhABrnVdaDqHpOCjh6iYhdUni5IacBkZqHjjQnZiMwr7l/GZs6MLvZ5QHpA+GG+vvgStPUlKri5Z9O8Ijh3xiQMamEmq7eQOJ5PmRfJNRTj119s5jo+c55QFWdk+esv2eTr1xcVK98bsmpj62lzHGuemVy0A/kRdWIVU2g2drzqkYboMgQ+kOAaq5UYthTZQU+nfrcRRCjLuYB9U9+moNMMTs3SW7AXQG5bifAbkquxnFwvnZzWaEINVUy8PeZc0r/zNmKmpMHv1gBzBDkYgKUmDQuPaYjzGqlIxc2T5+0EUqQQNcC9HrWGQOR412lGsS7LhZWYozfLxNG1GWPjyYH12tC/9kjWjjo5O7z7O10Ztqm88x60yIBsk9vBDmvjG8aJeE1tRLaZ9sARpR/lOqtQ9th9ZNC/DuO7LW1YJqyRKsZTDKEb+bwpYNH+te7O5rQWpSodyhFfuoWGPbjTqEfmV64TIkjG2wB7EEFzOBXyBTojyuPWmuw6ckEc1QXY0baTOzCghWMR68CJRdcVa+Rpf0EA3RvWlsD551fBNITx+iYToKKVZb75EWzn7od10nzgMnOMZ2MAI61vK/n1uamvhOk/sIa+Zrei8TQTUSRsIV6Ys9tdXNsTIxKZxOa3M3gm18Y6Siv39T0cUWfVYI5+IYmjSD8i
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: app

