apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: app
spec:
  encryptedData:
    password: AgCFN1VDmZLexHA+JAVWamyxVbkRVgAyBFOAF0jZAKvCSS5+sfgUl9H/otNiWIx1nUJxMr3czi+qcSiOIaf1uq3I+vxI9YiUMhzD9NEAHnwodszkhcn2gYN1U0btfzVJ0Q3T5CgR4sFUImtBPQixf1n07c8CM6h01I+3r0jACgJVZSWKbdXgRuLX7w36fwySi3l3mgmDjJI4fGI+aIA25Q6ByMDwN7SB9KZiyOaQB6Csa4DO5r+5Ap05ai2EHyYXmsTJcy5NPMX1sRjYPJiiJ5lEn0fgFq3TCInywstF7qXZ2u5awjGwzVz7waQLfi6bPYJWg406LVfRRiHeZHsb9794dU4eRF2jJUDrEX0Fo/jspTP5H8fyPOWAYQgTtjkPVrBt5e4S/fyFivWeq7ahd6D66wYxfugQKo0c6E7gYYHzqC5AfkvCkzJ6dWYz7mJZOmKeHDgeg6hVVkemCcEJIiDDQKnAY8nMDBUvsd9R3eA6CktlBi/p/mHp95c/cccmQCZdJvXl+82HLqrezdW2fvtulLTWqcJwvt9VSU8sPnCk9CmiPOVMZspsfoB0IslhwbzzIJuAIAj9kVfZIQaKgC216O4N02QmiCf2VxRrIaJqvg297+hLwHDIh9SAtA+CNVGpdIrC/oq9ELVi9ou0yyGVcHix8ht6bHNAma63eK4hYgrtC0oTs3PbOmydEKdgNgyzwQBJfQr8Tw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: app

