apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app

resources:
  - ../base
  - secrets.yaml

# patch config maps
configMapGenerator:
  - behavior: merge
    literals:
      - BACKEND_RESTPORT=3000
      - BACKEND_POSTGRESUSERNAME=postgres
      - BACKEND_JWTEXPIRESSEC=36000
    name: backend
  - behavior: merge
    literals:
      - ISSUER_ID=125344402375953606533377270523694284815265854046 # Demo issuer - https://etherscan.io/tx/0xfbf58513352fe0dc899544b66013adbacb90437210e0008ceeb7b9c9ecec5bdd#eventlog
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    name: issuer
  - behavior: merge
    literals:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
    name: postgres
