# This file contains the secrets that are used in the local k8s cluster
# DO NOT USE THIS FILE IN PRODUCTION
apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: app
type: Opaque
data:
  # if in config, BACKEND_ENABLELOGINEMAIL is enabled, then the following fields are required
  AWS_ACCESS_KEY_ID: mock_key_id
  AWS_SECRET_ACCESS_KEY: mock_secret_key
  BACKEND_POSTGRESPASSWORD: password
  BACKEND_JWTSECRETKEY: rzxlszyykpbgqcflzxsqcysyhljt
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: app
type: Opaque
data:
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: issuer
  namespace: app
type: Opaque
data:
  # Demo issuer - 0x15f4a32c40152a0f48E61B7aed455702D1Ea725e
  # echo -n 0xfd60ceb442aca7f74d2e56c1f0e93507798e8a6e02c4cd1a5585a36167fa7b03 | base64
  ISSUER_PK: MHhmZDYwY2ViNDQyYWNhN2Y3NGQyZTU2YzFmMGU5MzUwNzc5OGU4YTZlMDJjNGNkMWE1NTg1YTM2MTY3ZmE3YjAz
