apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
data:
  BACKEND_RESTPORT: "3000"
  BACKEND_POSTGRESUSERNAME: "postgres"
---
# TODO: manage secrets with a secret manager
apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  BACKEND_POSTGRESPASSWORD: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          envFrom:
            - configMapRef:
                name: backend
            - secretRef:
                name: backend
          image: backend
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: backend
