apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
data:
  BACKEND_RESTPORT: "3000"
  BACKEND_POSTGRESUSERNAME: "postgres"
  BACKEND_JWTEXPIRESSEC: "36000"
---
# TODO: manage secrets with a secret manager
apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  BACKEND_POSTGRESPASSWORD: password
  BACKEND_JWTSECRETKEY: rzxlszyykpbgqcflzxsqcysyhljt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          envFrom:
            - configMapRef:
                name: backend
            - secretRef:
                name: backend
          image: oyyblin/proof-pass-backend
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: backend
