# This bootstraps a Redis master and two Redis replicas. No persistence is
# enabled for the master and replicas for demo purposes.
kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-master
  namespace: app
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    app: redis
    role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
        - name: redis-master
          image: redis
          command: ["redis-server"]
          args:
            [
              "--save",
              "",
              "--appendonly",
              "no",
              "--stop-writes-on-bgsave-error",
              "no",
            ]
          ports:
            - name: redis-server
              containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: redis-master
  namespace: app
  labels:
    app: redis
    role: master
spec:
  ports:
    - port: 6379
      targetPort: redis-server
  selector:
    app: redis
    role: master
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-replica
  namespace: app
  labels:
    app: redis
    role: replica
spec:
  replicas: 2
  selector:
    app: redis
    role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
        - name: redis-replica
          image: registry.k8s.io/redis-slave:v2
          command: ["redis-server"]
          args:
            [
              "--save",
              "",
              "--appendonly",
              "no",
              "--stop-writes-on-bgsave-error",
              "no",
            ]
          ports:
            - name: redis-server
              containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: redis-replica
  namespace: app
  labels:
    app: redis
    role: replica
spec:
  ports:
    - port: 6379
      targetPort: redis-server
  selector:
    app: redis
    role: replica
