apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui
          env:
            - name: BASE_URL
              value: /swagger-ui
            - name: SWAGGER_JSON_URL
              # TODO: host this file on api server
              value: https://raw.githubusercontent.com/proof-pass/proof-pass/main/backend/api/openapi.yaml
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /swagger-ui
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /swagger-ui
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  namespace: swagger-ui
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: swagger-ui
