apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./sealed-secrets
  - ./secrets
  - ../base
  - gateway_api.yaml
  - gateway_frontend.yaml

# patch config maps
configMapGenerator:
  - behavior: merge
    literals:
      - BACKEND_ISSUERCHAINID=1
      - BACKEND_ENABLELOGINEMAIL=true
      - BACKEND_RESTPORT=3000
      - BACKEND_POSTGRESUSERNAME=postgres
      - BACKEND_JWTEXPIRESSEC=36000
    name: backend
    namespace: app
  - behavior: merge
    literals:
      - ENV=production
    name: frontend
    namespace: app
  - behavior: merge
    literals:
      - ISSUER_ID=510272064749248819730000788014960283495993569847
    name: issuer
    namespace: app
  - behavior: merge
    literals:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
    name: postgres
    namespace: app
