# TODO: this is for testing in production env only - we will deprecate this and reset database in production
apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  BACKEND_POSTGRESPASSWORD: password
  BACKEND_JWTSECRETKEY: rzxlszyykpbgqcflzxsqcysyhljt
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: issuer
type: Opaque
data:
  # Demo issuer - 0x15f4a32c40152a0f48E61B7aed455702D1Ea725e
  # echo -n 0xfd60ceb442aca7f74d2e56c1f0e93507798e8a6e02c4cd1a5585a36167fa7b03 | base64
  ISSUER_PK: MHhmZDYwY2ViNDQyYWNhN2Y3NGQyZTU2YzFmMGU5MzUwNzc5OGU4YTZlMDJjNGNkMWE1NTg1YTM2MTY3ZmE3YjAz
