openapi: 3.0.3
info:
  title: ZK Ticketing API
  version: 0.0.1
servers:
  - url: http://localhost:3000/api/v1
paths:
  /health:
    get:
      summary: Check the health of the API
      responses:
        "200":
          description: The API is healthy
  /events:
    get:
      summary: Get list of events
      responses:
        "200":
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
  /events/{eventId}:
    get:
      summary: Get event details
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Event details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
  /users/request-verification-code:
    post:
      summary: Request an email verification code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserEmailVerificationRequest"
      responses:
        "200":
          description: Verification code sent successfully
  /users/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /users/me:
    get:
      summary: Get user details
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User details retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /users/update:
    put:
      summary: Update user details
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
      responses:
        "200":
          description: User details updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        admin_code:
          type: string
    UserEmailVerificationRequest:
      type: object
      properties:
        email:
          type: string
    UserLogin:
      type: object
      properties:
        email:
          type: string
        code:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        identity_commitment:
          type: string
        encrypted_internal_nullifier:
          type: string
        encrypted_identity_secret:
          type: string
        created_at:
          type: string
          format: date-time
    UserUpdate:
      type: object
      properties:
        identity_commitment:
          type: string
        encrypted_internal_nullifier:
          type: string
        encrypted_identity_secret:
          type: string
