openapi: 3.0.3
info:
  title: ZK Ticketing API
  version: 0.0.1
servers:
  - url: http://localhost:3000/api/v1
paths:
  /health:
    get:
      summary: Check the health of the API
      responses:
        "200":
          description: The API is healthy
  /events:
    get:
      summary: Get list of events
      responses:
        "200":
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
  /events/{eventId}:
    get:
      summary: Get event details
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Event details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        admin_code:
          type: string
